# Generated by Django 3.0.7 on 2020-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='desc',
            field=models.TextField(),
        ),
    ]
