# Generated by Django 3.0.7 on 2020-06-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200610_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=400)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('summary', models.CharField(default='VNM', max_length=400)),
                ('post', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
