# Generated by Django 3.0.7 on 2020-06-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200610_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('f_name', models.CharField(max_length=70)),
                ('l_name', models.CharField(max_length=70)),
                ('position', models.CharField(max_length=100)),
                ('twitter', models.CharField(default='https://twitter.com/', max_length=200)),
                ('fb', models.CharField(default='https://www.facebook.com/', max_length=200)),
                ('google', models.CharField(default='https://plus.google.com/', max_length=200)),
                ('linkdn', models.CharField(default='"https://www.linkedin.com/', max_length=200)),
            ],
        ),
    ]
